import { AppConfig, GeneratedFile } from '../types';

export const generateFiles = (config: AppConfig): GeneratedFile[] => {
  const files: GeneratedFile[] = [];

  // 1. Manifest.json (PWA)
  const manifest = {
    name: config.name,
    short_name: config.name.replace(/\s+/g, ''),
    start_url: config.url,
    display: config.permissions.fullscreen ? "standalone" : "minimal-ui",
    background_color: "#ffffff",
    theme_color: config.color,
    description: config.description,
    icons: [
      {
        src: "icon.png",
        sizes: "512x512",
        type: "image/png"
      }
    ]
  };
  files.push({
    name: 'manifest.json',
    content: JSON.stringify(manifest, null, 2),
    language: 'json'
  });

  // 2. Electron package.json
  const packageJson = {
    name: config.name.toLowerCase().replace(/\s+/g, '-'),
    version: "1.0.0",
    description: config.description,
    main: "main.js",
    scripts: {
      "start": "electron .",
      "build:android": "npx cap add android && npx cap run android",
      "build:ios": "npx cap add ios && npx cap run ios"
    },
    dependencies: {
      "electron": "^28.0.0",
      "@capacitor/core": "^5.0.0",
      "@capacitor/cli": "^5.0.0",
      "@capacitor/android": "^5.0.0",
      "@capacitor/ios": "^5.0.0"
    }
  };
  files.push({
    name: 'package.json',
    content: JSON.stringify(packageJson, null, 2),
    language: 'json'
  });

  // 3. Electron main.js
  const permissionsList = Object.entries(config.permissions)
    .filter(([_, enabled]) => enabled)
    .map(([key]) => key);

  const mainJs = `
const { app, BrowserWindow, session, systemPreferences } = require('electron');
const path = require('path');

function createWindow() {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    title: "${config.name}",
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
    }
  });

  // Load the remote URL
  win.loadURL('${config.url}');

  // Permission Handling
  session.defaultSession.setPermissionRequestHandler((webContents, permission, callback) => {
    const allowedPermissions = ${JSON.stringify(permissionsList)};
    
    // Map Electron permission strings to our config keys if necessary
    // Common mappings: 'media' -> camera/microphone, 'geolocation' -> geolocation
    
    let isAllowed = false;
    
    if (permission === 'media') {
      if (allowedPermissions.includes('camera') || allowedPermissions.includes('microphone')) {
        isAllowed = true;
      }
    } else if (permission === 'geolocation' && allowedPermissions.includes('geolocation')) {
      isAllowed = true;
    } else if (permission === 'notifications' && allowedPermissions.includes('notifications')) {
      isAllowed = true;
    }

    if (isAllowed) {
      callback(true);
    } else {
      console.log(\`Permission \${permission} denied.\`);
      callback(false);
    }
  });

  ${config.permissions.fullscreen ? 'win.setFullScreen(true);' : ''}
}

app.whenReady().then(() => {
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
  `.trim();

  files.push({
    name: 'main.js',
    content: mainJs,
    language: 'javascript'
  });

  // 4. Capacitor Config (Mobile)
  const appId = `com.${config.name.toLowerCase().replace(/[^a-z0-9]/g, '')}.app`;
  const capacitorConfig = {
    appId: appId,
    appName: config.name,
    webDir: "dist",
    server: {
      url: config.url,
      cleartext: true
    },
    plugins: {
      SplashScreen: {
        launchShowDuration: 0
      }
    }
  };
  files.push({
    name: 'capacitor.config.json',
    content: JSON.stringify(capacitorConfig, null, 2),
    language: 'json'
  });

  // 5. Android Manifest (Preview)
  let androidPerms = '';
  if (config.permissions.camera) androidPerms += '    <uses-permission android:name="android.permission.CAMERA" />\n';
  if (config.permissions.microphone) androidPerms += '    <uses-permission android:name="android.permission.RECORD_AUDIO" />\n';
  if (config.permissions.geolocation) {
    androidPerms += '    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />\n';
    androidPerms += '    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />\n';
  }
  if (config.permissions.notifications) androidPerms += '    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />\n';

  const androidManifest = `
<!-- This file is auto-generated by Capacitor usually, but here is the configuration with your permissions injected -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${appId}">

    <uses-permission android:name="android.permission.INTERNET" />
${androidPerms}
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        
        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name="com.getcapacitor.BridgeActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:exported="true">
            
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            
        </activity>
    </application>
</manifest>
`.trim();

  files.push({
    name: 'AndroidManifest.xml',
    content: androidManifest,
    language: 'xml'
  });

  // 6. iOS Info.plist (Preview)
  let iosKeys = '';
  if (config.permissions.camera) {
    iosKeys += `
    <key>NSCameraUsageDescription</key>
    <string>This app requires camera access to function properly.</string>`;
  }
  if (config.permissions.microphone) {
    iosKeys += `
    <key>NSMicrophoneUsageDescription</key>
    <string>This app requires microphone access to function properly.</string>`;
  }
  if (config.permissions.geolocation) {
    iosKeys += `
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>This app requires location access to function properly.</string>`;
  }

  const infoPlist = `
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDisplayName</key>
    <string>${config.name}</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UILaunchStoryboardName</key>
    <string>LaunchScreen</string>
    <key>UIMainStoryboardFile</key>
    <string>Main</string>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>armv7</string>
    </array>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UIViewControllerBasedStatusBarAppearance</key>
    <true/>
    ${config.permissions.fullscreen ? '<key>UIStatusBarHidden</key><true/>' : ''}
    ${iosKeys}
</dict>
</plist>
`.trim();

  files.push({
    name: 'Info.plist',
    content: infoPlist,
    language: 'xml'
  });

  return files;
};